### ISSUE TITLE
Unnecessary `target` attribute should cause an error

### ISSUE THREAD

**Issue by hobofan** [hobofan/ambassador#10]
I found this in one of the tests that currently passes:
```rs
#[derive(Delegate)]
#[delegate(Shout, target = "bar")]
pub enum Either<A: Shout, B: Shout> {
    Left(A),
    Right(B),
}
```

The `target` attribute isn't needed and doesn't point to anything, so it should throw an error, so we avoid confusing code.

**Comment by vi** [comment]
I think unnecessary target attributes should be supported (for example, for some code that is generated automatically). For similar reasons as trailing commas.

If unnecessary target attributes cause are known to cause errors for users then additional attribute like `allow_unnessesary_target` can be added (or ideally when proc macros gain ability to use custom lints, it can be just a deny-by-default lint).
