### ISSUE TITLE
inline delegated trait method calls

### ISSUE THREAD

**Issue by Swoorup** [hobofan/ambassador#47]
Should the generated trait method calls be marked with inline attribute by default?

**Comment by dewert99** [comment]
Sorry for the slow response. I just checked the expansion of the standard library derive macros and they seem to use `#[inline]`, so I think this is a good idea.

**Comment by vigna** [comment]
In fact, it would be interesting to have an option (feature?) to get `#[inline(always)]`. These are delegations—they should literally disappear. We're seeing some chains of delegations alive in spide of the `[inline]`, and that hurts performance.
